import glob

fastq_files = glob.glob("data/*gz")
fastq_pe_html = [fastq.replace(".fq.gz", ".pe.qc_fastqc.html") for fastq in fastq_files]
fastqc_output = [fastq.replace(".fq.gz", "_fastqc.html") for fastq in fastq_files] + fastq_pe_html

rule all:
  input:
    "multiqc_report.html"
    
rule fastqc_a_file:
  input:
    "{filename}.fq.gz"
  output:
    "{filename}_fastqc.html",
    "{filename}_fastqc.zip"
  conda:
    "binder/env_fastqc.yml"
  shell:
    "fastqc {input}"
    
rule run_multiqc:
  input:
    fastqc_output
  output:
    "multiqc_report.html",
    directory("multiqc_data")
  shell:
    "multiqc data"

rule trim_reads:
  input:
    "{filename}_1.fq.gz",
    "{filename}_2.fq.gz"
  output:
    "{filename}_1.pe.qc.fq.gz",
    "{filename}_1.se.qc.fq.gz",
    "{filename}_2.pe.qc.fq.gz",
    "{filename}_2.se.qc.fq.gz"
  shell:
    """trimmomatic PE {input} {output} LEADING:2 TRAILING:2 \
      SLIDINGWINDOW:4:15 \
      MINLEN:25"""

rule clean:
  shell:
    "rm -r {fastqc_output} multiqc_report.html"